[package]
name = "sora"
version = "0.0.1"
authors = ["Gareth Poole"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"
spin = "0.3.4"

[dependencies.collections]
path = "stdlib/libcollections"

[dependencies.gpmalloc]
path = "libgpmalloc"