[package]
name = "collections"
version = "0.0.0"
authors = ["Rust Developers"]

[lib]
crate-type = ["rlib"]

[dependencies.rustc_unicode]
path = "../librustc_unicode"

[dependencies.alloc]
path = "../liballoc"